variables:
  buildConfiguration: 'Release'
jobs:
- job: Angular
  steps:
  - task: DeleteFiles@1
    displayName: 'Delete JUnit files'
    inputs:
      SourceFolder: src/angular7/junit
      Contents: 'TEST*.xml'
  
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: install
      workingDir: src/angular7
  
  - task: Npm@1
    displayName: 'Build Angular'
    inputs:
      command: custom
      customCommand: run build -- --prod
      workingDir: src/angular7
  
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'angular'
      targetPath: 'src/angular7/dist'
  
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'src/angular7/dist'
      ArtifactName: angular2
  